version: "3"

networks:
  network:
    driver: bridge

services:
  nginx:
    image: nginx:1.18-alpine
    restart: always
    tty: true
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network
    depends_on:
      - api

  api:
    image: roberto0arruda/php-fpm
    container_name: challenge-api
    volumes:
      - .:/var/www
    expose:
      - 9000
    networks:
      - network
    # depends_on:
    #   - mysql

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./vendor/mysqldb:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    expose:
      - 3306
    networks:
      - network
